title: Bottles
author: BottlesDev
email: mail@usebottles.com
description: >-
  ğŸ’« Easily manage ğŸ·prefix in a new way! (Run Windows software and games on Linux)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

