title: Bottles
description: Easily run Windows software on Linux with ğŸ· Bottles!
author: Bottles Developers
email: mail@usebottles.com
logo: /uploads/logo.svg?v4

assets: /assets
uploads: /uploads

permalink: /blog/:title/
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

navigation:
    - link: "https://docs.usebottles.com/"
      name: ğŸ“• Docs
    - link: "https://github.com/bottlesdevs/Bottles/issues/new/choose"
      name: Bug report
    - link: "https://hosted.weblate.org/engage/bottles/"
      name: Help translating
    - link: "https://github.com/bottlesdevs/"
      name: ğŸš€ GitHub
    - link: "/appstore/"
      name: Apps
    - link: "/database/"
      name: Database
    - link: "/blog/"
      name: Blog
    - link: "https://forum.usebottles.com"
      name: Forums
    - link: "/funding/"
      name: Funding

plugins:
  - jekyll-feed
