title: Bottles
description: Easily run Windows software on Linux with üç∑ Bottles!
author: Bottles Developers
email: mail@usebottles.com
logo: /uploads/logo.svg

assets: /assets
uploads: /uploads

markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed