title: Bottles
description: Easily run Windows software on Linux with üç∑ Bottles!
author: Bottles Developers
email: mail@usebottles.com
logo: /uploads/logo.svg?v2

assets: /assets
uploads: /uploads

permalink: /blog/:title/
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

navigation:
    - link: "https://docs.usebottles.com/"
      name: Documentation
    - link: "https://github.com/bottlesdevs/Bottles/issues/new/choose"
      name: Bug Report
    - link: "https://hosted.weblate.org/engage/bottles/"
      name: Help Translating
    - link: "https://github.com/bottlesdevs/"
      name: üöÄ GitHub
    - link: "/database/"
      name: Database
    - link: "/blog/"
      name: Blog
    - link: "/funding/"
      name: Funding

plugins:
  - jekyll-feed